export const helpTopics = [
  {
    id: 'lab',
    title: 'Test lab: checks, workflows and environments',
    summary: 'Turn captured requests into repeatable tests with guided review.',
    steps: [
      'Choose Test lab in the sidebar or command palette. Create test in request details or an editor copies that request into an independent suite. Nothing is sent until Review suite, then Start suite.',
      'Add checks for status, response headers, JSON values, response text and duration. JSON selectors use JSON Pointer: /user/id or /items/0/name. Escape a slash in a key with ~1 and a tilde with ~0. Equality supports scalar values. Use type to check objects or arrays.',
      'Add steps from captures or create a blank request. Extract an existing scalar JSON/header value after a passing step, name it userId, then use {{userId}} in a later path, header or quoted JSON value. Whole JSON placeholders preserve extracted numeric/boolean/null types. Forward references and duplicate variable names are rejected.',
      'Environments store text constants locally. A blank override keeps captured origins. An override changes only origins, retaining paths and queries. To prevent forwarding credentials accidentally, static credential headers must be replaced with environment placeholders or excluded when changing origin.',
      'Save with Ctrl/Cmd + S. Review with Ctrl/Cmd + Enter. The review lists every destination and any omitted headers. Runs use extension context, no ambient cookies, no redirects/retries, a 25-second timeout and a 1 MB response limit. Keep the Test lab tab open; closing/reloading interrupts execution.',
      'Every check must pass. Missing, binary, truncated or invalid JSON bodies produce inconclusive checks and fail the step. Extracted values and response bodies are not stored in reports. Reports keep the latest 25 runs per workspace; export JSON or JUnit XML.',
      'Suite exports mask recognized secrets and omit environments. Imports create a separate suite in the current workspace and never run automatically. Replace redacted values before running. General history backups do not include Test lab data; export suites separately.',
      'Security in request details performs passive checks on one capture. Findings are review prompts, not confirmed vulnerabilities. Prepare AI / bug-report context gives editable, redacted text to review and copy; no AI service is connected or contacted.',
    ],
    note: 'Suite definitions and environments may contain credentials and are stored unencrypted. Capture deletion does not delete independent suites; deleting a workspace or all stored data does. Up to 100 suites and 30 environments per workspace; 30 sequential steps and 50 checks per step. No request is automatically replayed after interruption.',
  },
  {
    id: 'runner',
    title: 'Timed API runs',
    summary: 'Paced requests, variables and local performance measurements.',
    steps: [
      'Open a request in a new editor tab. Edit its URL, headers and body, then choose Timed run. Enter a request count, time window, concurrency and timeout. Review run previews the target; Start run sends traffic.',
      '10,000 requests over 1 minute plans 166.67 starts per second. Slots are evenly paced, or linearly ramped when configured. In-flight requests may finish after the window. Concurrency or timer delays can leave slots unsent; the report shows those counts instead of catching up in a burst.',
      'Advanced options include a status range, latency budget, response read limit, consecutive-failure circuit breaker and stopping on HTTP 429. Stop run aborts active requests and prevents later starts. The runner never follows redirects or retries automatically.',
      'Use {{index}}, {{uuid}}, {{timestamp}} and {{randomInt}} in the request. Define custom variables or cycle JSON data rows. Index starts at 1 and follows scheduled slots. Quote placeholders in JSON; whole placeholders preserve numeric/boolean types. URL and form values are encoded, while headers and plain text are literal. Variables cannot change the origin.',
      'Open Variables & data rows for a three-step guide. Choose an included field from your actual request, then Insert placeholder & define value. The guide adds its current nonsecret value as a starting example; numeric, boolean and null JSON values get typed data rows. Edit those values, then check the first three request previews. No traffic is sent by the guide.',
      'Custom variables are constant text values. Data rows override them and cycle by scheduled slot; enter a JSON array such as [{"bodyName":"Mihir"},{"bodyName":"Ada"}]. Back to editor keeps your run configuration while this tab remains open. Placeholders are saved in the draft; custom values and data rows are not persisted after the tab reloads.',
      'Analytics cover start rate, completed outcomes, status counts, decoded bytes, attempt duration, headers received, body read, start delay and timer lag. Percentiles use bounded histograms; every outcome contributes. Samples keep only the last 100 attempts and first 20 failures.',
      'The extension worker runs independently of editor tabs. Close/reopen editors freely, and use Timed runs in the dashboard to monitor or stop. The latest 50 reports stay local. Export Report JSON for all aggregate metrics or Sample CSV for the bounded samples.',
    ],
    note: 'This runner uses extension context without page cookies. Closing Chrome or reloading the extension interrupts a run; saved checkpoints are recovered without repeating requests. DNS/TLS, exact wire timing, server processing and computer-wide CPU/memory are unavailable. Response bodies and request credentials are not stored in run reports. Browser and OS scheduling prevent a guaranteed rate on every computer.',
  },
  {
    id: 'start',
    title: 'Getting started',
    summary: 'From your first capture to a replay.',
    steps: [
      'On first installation, ApiSip opens a setup page. Choose Allow website access and approve Chrome’s permission prompt. Granting access alone leaves recording paused; choose Start recording when ready. You can also continue without capture and grant access later.',
      'Open an HTTP(S) webpage. Press Alt + Shift + C to start or stop recording, or click ApiSip and use Start capture in the inspector. Chrome owns the recording shortcut, so it works with the inspector closed. Customize it at chrome://extensions/shortcuts if another extension or the OS uses those keys.',
      'Browse the webpage or trigger its API calls. Requests appear live. The icon badge counts the configured capture scope.',
      'Select a request to inspect it. Use the search bar or Filters to narrow the list, then open Replay to edit and send it.',
      'Use the ? beside a section for guidance. Hold Ctrl, Cmd or Alt alone for one second to see shortcuts. Release to hide them.',
    ],
    note: 'Captured data stays in this browser profile. Replay sends the edited request to the URL you choose.',
  },
  {
    id: 'capture',
    title: 'Capture and badge',
    summary: 'Choose the source and the data Chrome can expose.',
    steps: [
      'Current tab follows your most recently active supported webpage. Opening this inspector preserves that source. All tabs observes permitted web tabs.',
      'Recording pauses or resumes capture. The toolbar icon shows a teal pulse while recording and a gray pause symbol when stopped. Its tooltip also names the state; the badge keeps your saved request count. Alt + Shift + C toggles recording from any browser tab.',
      'Response capture is enabled by default on new installations for available bodies, detailed timing and WebSocket frames; Chrome shows a debugging notice after you start recording. Existing preferences are preserved. Disable the switch for passive metadata capture.',
      'Passive capture includes available request data, headers, status and total timing, but no response bodies. Start response capture before repeating the request.',
      'Settings > Capture controls scope, badge count, body limits and navigation cleanup. Sessions normally continue across reloads and SPA navigation.',
    ],
    note: 'Internal Chrome pages, traffic before capture and some worker/cache events are unavailable. DevTools or another debugger can prevent response capture. Check Settings > Diagnostics.',
  },
  {
    id: 'requests',
    title: 'Request list and selection',
    summary: 'Navigate, select and organize thousands of requests.',
    steps: [
      'Click a row to inspect it. Focus the list with Alt + Shift + R; Up/Down and Home/End move between requests. Space toggles the focused row checkbox.',
      'The header checkbox selects every matching request, including rows off screen. A dash means a partial selection. Click again to deselect matching requests; Ctrl/Cmd + A also selects them when the list is focused.',
      'The selection bar exports, deletes or adds selected requests to a collection. Selection can include requests outside your current filters; Deselect clears the entire selection.',
      'Click column labels to sort. Columns lets you hide or reorder fields. Drag dividers to resize, or focus a divider and use Left/Right. Group organizes endpoints without changing their URLs.',
      'Right-click a request or press Shift + F10 in the focused list for actions. Stars save requests; pinning keeps them near the top. Jump to latest preserves your scroll position until you choose to move.',
      'Right-click a populated table cell and choose Add filter to match its value, or double-click the cell. For example, Type = XHR matches both XHR and XMLHttpRequest. The rule is added with AND to your current filter. Left/Right moves between cells of the selected row; Enter filters the focused cell and Shift + F10 opens its menu.',
    ],
    note: 'Red delete and clear actions require confirmation before stored history is removed. Deleting history does not stop recording; new requests continue to arrive.',
  },
  {
    id: 'filters',
    title: 'Search and filters',
    summary: 'Find endpoints with text or compound expressions.',
    steps: [
      'Ctrl/Cmd + K or F focuses search. Search covers URL, method, headers, query, bodies, tags and notes. Quick filters show errors, 4xx, 5xx, slow or large responses.',
      'Open Filters. Add rules and nested groups: ALL means AND, ANY means OR; NOT reverses a group. Search field/operator/value dropdowns, then press Enter to choose. Common values and captured metadata are suggested; recognized secrets are excluded. XHR and XMLHttpRequest are equivalent.',
      'Fields can include a header or query key, such as requestHeader.authorization or queryParam.page. Type a custom field in the field picker and press Enter.',
      'After choosing a value, Enter again applies the filter. Expression mode accepts statements such as method = POST AND status >= 400; Enter applies and Shift + Enter adds a line. Save a filter with a name to reuse it from the sidebar.',
      'Table cell filters apply immediately and preserve existing OR/NOT groups. Repeating the same cell filter does not add a duplicate. Missing values and masked secrets do not offer a cell filter; time and size use their exact underlying values.',
    ],
    note: 'Regex syntax is deliberately restricted to avoid slow searches. A missing response body cannot match body content. Invalid expressions explain what to fix.',
  },
  {
    id: 'workspaces',
    title: 'Workspaces and sessions',
    summary: 'Keep projects and capture runs separate.',
    steps: [
      'Search the workspace picker to switch projects. New workspace creates a separate home for sessions, collections and saved filters.',
      'Create a session with the + beside Sessions or Alt + Shift + N. Select a session to view and record into it; All sessions shows the workspace history.',
      'Use a three-dot menu to rename, archive or delete entities, or duplicate a workspace. Menus close on outside click, Escape or after an action.',
      'Archive keeps a session available for reference. Delete removes its related data after confirmation. Export a workspace or session first if you need a backup.',
    ],
    note: 'Chrome assigns separate histories to separate browser profiles and unpacked installation folders. Keep using the same extension folder.',
  },
  {
    id: 'collections',
    title: 'Saved APIs, collections and tags',
    summary: 'Keep useful requests ready to revisit.',
    steps: [
      'Click a star or choose Save request. Saved APIs shows favorites. Pinned requests, favorites and collection requests are protected from automatic retention cleanup.',
      'Create a collection, select requests and choose Add to collection. Search the collection chooser to find the destination.',
      'Overview lets you edit tags and notes. Tags and notes participate in global search; tag filters can isolate a debugging task.',
      'Save in the request editor creates an editable saved request. A saved request is separate from an executed replay and does not send network traffic.',
    ],
    note: 'Deleting a collection removes its organization; requests remain in history. Read each confirmation before deleting.',
  },
  {
    id: 'details',
    title: 'Inspect requests and responses',
    summary: 'Read every available field safely.',
    steps: [
      'Overview shows URL, status, source, timing, tags and notes. Request/Response summarize available data; Headers supports search, copying and explicit secret reveal.',
      'Query lists decoded and encoded values. Body offers pretty/raw views, search, JSON tree expansion and copying. HTML and scripts are displayed as inert text.',
      'Cookies shows exposed cookie headers. Timing shows available durations; Security explains transport/capture information. Raw reconstructs exposed request and response fields.',
      'For GraphQL, inspect operation name, query and variables in the body. Messages shows bounded WebSocket frames when response capture exposes them.',
      'Use Left/Right in the section tabs. Copy buttons copy the currently shown representation; reveal secrets explicitly when needed.',
    ],
    note: 'Unavailable or truncated data is labeled. Raw mode is a reconstruction, not an exact network packet. Missing sizes and timings are not invented.',
  },
  {
    id: 'replay',
    title: 'Edit, replay and compare',
    summary: 'Change a request and inspect the real result.',
    steps: [
      'Select a captured request and open Replay. Edit method, URL, query rows, headers or body. Format/validate JSON before sending when helpful.',
      'Open eye means include; closed eye means exclude from sending and blur the value. Toggle individual headers, JSON properties (including nested groups and array items), form rows or the entire body. Excluding a group also excludes its children. Choices stay in saved drafts and apply to timed runs and code snippets. Restore the eyes to edit a blurred raw body.',
      'Lock/Reveal controls only mask secrets on screen; they do not change request inclusion. Chrome can still add or control transport headers. Raw text/XML/HTML/binary/multipart bodies use the whole-body eye; individual field controls are for JSON and URL-encoded forms up to 1 MB (300 visible fields). Blur is a display effect, not encryption.',
      'Automatic prefers the original browser tab when available. Browser uses cookies and CORS rules from the source tab. Extension uses granted host access and omits ambient cookies.',
      'Click Send or press Ctrl/Cmd + Enter in the editor. A replay can change data at the target API, so review its method, URL and body first.',
      'Replay history stores up to 30 results. Choose a replay to inspect response/error, duration, omitted-header warnings and structural differences from the original.',
    ],
    note: 'Chrome controls forbidden headers. Closed tabs, changed origins, CORS and missing permission can block replay. Incomplete/binary/multipart-file bodies must be replaced before sending. No automatic retry switches contexts.',
  },
  {
    id: 'editor',
    title: 'Editor in a new tab',
    summary: 'Give a request its own editing workspace.',
    steps: [
      'In Replay, click Open in new tab to carry over the method, URL, headers, query, body and selected replay context. The icon in the request heading opens the original request in a new editor.',
      'Wait for Draft saved locally before reloading or closing. Incomplete URLs and unfinished bodies can be saved as drafts; valid requests are required when sending or saving to Saved APIs.',
      'Send or Ctrl/Cmd + Enter uses the existing replay engine. Responses, headers and comparisons appear beside the editor, and replay history is shared with the original request.',
      'Open inspector returns to the dashboard while keeping this editor open. Save as new request creates a favorite for export or collections. Reset restores the captured request.',
      'Each opened editor gets an independent draft. Duplicating the same editor URL shares that draft; conflicting writes are rejected so another tab cannot silently overwrite your changes.',
      'Discard draft removes only its edits after confirmation. Deleting its source request, session, workspace or history also removes the related drafts.',
    ],
    note: 'Drafts stay in IndexedDB and protect their source from automatic cleanup. Save as new request to include edits in an export. Browser replay still requires its original source tab and permissions.',
  },
  {
    id: 'export',
    title: 'Copy, code, export and import',
    summary: 'Move debugging evidence into your workflow.',
    steps: [
      'Copy individual fields or use Copy everything for structured JSON. Code offers searchable language generators; Ctrl/Cmd + Shift + C copies cURL for the selected request.',
      'Export selected, filtered, session, workspace or full history as JSON, CSV, Markdown, HAR or text. Pick the included headers, bodies, cookies, timing and metadata.',
      'Recognized secrets are excluded by default. Including sensitive values requires an explicit choice for each export. Review arbitrary free-text tokens before sharing.',
      'The import button accepts validated internal JSON backups and HAR files up to 100 MB. Imported requests receive new identities and cannot replay into an unrelated old browser tab.',
    ],
    note: 'HAR and snippets can only describe exposed data. Windows CMD cURL output is intended for a .cmd file. Large histories may need smaller export scopes.',
  },
  {
    id: 'analytics',
    title: 'Traffic insights',
    summary: 'Understand performance from local observations.',
    steps: [
      'Open Insights to summarize the current workspace/session and filters.',
      'Review request/error counts, measured latency, known transfer size, status/type/domain distributions and requests over time.',
      'Inspect largest responses, slow endpoints and frequent endpoint groups. Select an entry to return to the request details.',
      'P95 appears after 20 measured requests; P99 after 100. Missing timings and sizes remain unavailable.',
    ],
    note: 'Statistics describe captured traffic only. Filters and capture gaps affect the sample.',
  },
  {
    id: 'settings',
    title: 'Settings, privacy and diagnostics',
    summary: 'Control capture, storage and appearance.',
    steps: [
      'Capture: scope, badge mode/filter, maximum body size, default replay context and navigation cleanup. Click Save settings to apply changes.',
      'Privacy & storage: masking, retention days, maximum requests and approximate storage budget. Favorites, pins and collections can exceed retention limits.',
      'Export: choose default content. Appearance: System, Light or Dark. Shortcuts: review the keyboard reference.',
      'Diagnostics: inspect site access, debugger attachment, queued writes and recent errors. Retry debugger attachment after resolving a conflict.',
      'Clear session/workspace/history or all stored data through confirmed actions. Data is local but unencrypted; display masking is not encryption.',
    ],
    note: 'No telemetry, cloud sync or hidden remote API. The extension works offline for stored history; replay needs access to the chosen endpoint.',
  },
  {
    id: 'shortcuts',
    title: 'Keyboard reference',
    summary: 'Keep your hands on the keyboard.',
    steps: [
      'Hold Ctrl, Cmd or Alt alone for one second to reveal shortcuts without moving focus. Release the key, press another key or leave the window to dismiss the hint.',
      'Tab and Shift + Tab move through controls. Menus use arrows, Home/End, Enter and Escape. Searchable pickers use typing, arrows and Enter; Escape cancels and Tab moves on.',
      'Global shortcuts run while the inspector is active and no dialog is open. Text fields preserve normal editing and selection. Chrome or OS-reserved shortcuts may take precedence.',
    ],
    note: 'Alt + Shift + A opens the extension through Chrome. Configure that command at chrome://extensions/shortcuts if it conflicts.',
  },
  {
    id: 'about',
    title: 'About and creator',
    summary: 'ApiSip, by Mihir Bhadak.',
    steps: [
      'A local-first network inspector built for developers who want to capture, understand and replay their API traffic.',
      'If ApiSip helps your workflow, you can support its development through the optional Buy me a coffee link below. Every feature remains available without a contribution.',
    ],
    note: 'Social and support links open external websites only when you click them. No payment widget or tracking script is loaded inside the extension.',
  },
] as const;
export type HelpTopic = (typeof helpTopics)[number]['id'];
